version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
